config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  resources :ideas do
    resources :votes
  end
  root to: 'ideas#welcome'
end

app/models/idea.rb
# == Schema Information
#
# Table name: ideas
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  content    :text
#  title      :string
#  first_name :string
#  last_name  :string
#  timeout_at :datetime
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Idea < ActiveRecord::Base
  validates :content, :title, :first_name, :last_name, presence: true

  has_many :votes

  after_create :timeout

  def timeout
    self.timeout_at = Time.zone.now + 1.week
    self.save
  end

  def up_votes
    self.votes.where(state: true)
  end

  def down_votes
    self.votes.where(state: false)
  end

  def self.active
    self.where('timeout_at > ?', Time.zone.now)
  end

end

app/models/vote.rb
# == Schema Information
#
# Table name: votes
#
#  id         :integer          not null, primary key
#  idea_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  state      :boolean
#

class Vote < ActiveRecord::Base
  belongs_to :idea

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :set_idea, only: [:show, :edit, :update, :destroy]

  def welcome

  end

  # GET /ideas
  # GET /ideas.json
  def index
    @idea = Idea.new
    if cookies[:voted_ideas].nil?
      cookies[:voted_ideas] = ""
    end
    @ideas = Idea.active.all

    @past_ideas = Idea.all - @ideas
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
  end

  # GET /ideas/new
  def new
    @idea = Idea.new
  end

  # GET /ideas/1/edit
  def edit
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = Idea.new(idea_params)

    respond_to do |format|
      if @idea.save
        format.html { redirect_to ideas_url, notice: 'Nové hlasování bylo vytvořeno.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /ideas/1
  # PATCH/PUT /ideas/1.json
  def update
    respond_to do |format|
      if @idea.update(idea_params)
        format.html { redirect_to @idea, notice: 'Idea was successfully updated.' }
        format.json { render :show, status: :ok, location: @idea }
      else
        format.html { render :edit }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea.destroy
    respond_to do |format|
      format.html { redirect_to ideas_url, notice: 'Idea was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idea
      @idea = Idea.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def idea_params
      params.require(:idea).permit(:user_id, :content, :title, :first_name, :last_name, :timeout_at)
    end
end

app/controllers/votes_controller.rb
class VotesController < InheritedResources::Base

  def new
    if cookies[:voted_ideas].split(',').include?(params[:idea_id])
      respond_to do |format|
        format.html { redirect_to ideas_url, alert: 'You have already voted.' }
      end
    else
      @idea = find_idea
      @vote = @idea.votes.new
    end
  end

  def index
    @votes = find_idea.votes
  end

  def show
    @vote = find_vote
  end

  def edit
    @vote = find_vote
  end

  def update
    @vote = find_vote

    if @vote.update(vote_params)
      redirect_to(@vote)
    else
      render('edit')
    end
  end

  def create
    @vote = Vote.new(vote_params)

    respond_to do |format|
      if @vote.save
        puts cookies[:voted_ideas]
        if cookies[:voted_ideas].nil?
          cookies[:voted_ideas] = @vote.idea.id
        else
          cookies[:voted_ideas] = cookies[:voted_ideas] + "," + @vote.idea.id.to_s
        end
        out = 'Hlasovali jste pro návrh.'
        out = 'Hlasovali jste proti návrhu.' unless @vote.state
        format.html { redirect_to ideas_url, notice: out }
      else
        format.html { render :new }
      end
    end
  end

  private

  def find_vote
    @vote = find_idea.votes.find(params[:id])
  end

  def find_idea
    @idea = Idea.find(params[:idea_id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def vote_params
    params.require(:vote).permit(:idea_id, :state)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/ideas/_form.html.erb
<%= simple_form_for(@idea) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title, label: "Název", placeholder: "Co chcete?", :input_html => {:maxlength => 30, :size => 40} %>
    <%= f.input :content, label: "Obsah", placeholder: "Proč by se to mělo řešit?", :size => 40, :max => 4 %>
    <%= f.input :first_name, label: "Křestní jméno" %>
    <%= f.input :last_name, label: "Příjmení"  %>
  </div>

  <p>Čas na hlasování je jeden měsíc.</p>

  <div class="form-actions">
    <%= f.button :submit, class: "btn" %>
  </div>
<% end %>

app/views/ideas/_modal_form.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
  aria-hidden="true">&times;</span></button>
  <h4 class="modal-title" id="myModalLabel">Vytvoř nový námět k hlasování</h4>
</div>
<%= simple_form_for(@idea) do |f| %>
  <div class="modal-body">

    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :title, label: "Název", placeholder: "Co chcete?", :input_html => {:maxlength => 15, :size => 40} %>
      <%= f.input :content, label: "Obsah", placeholder: "Proč by se to mělo řešit?", :size => 40, :max => 4 %>
      <%= f.input :first_name, label: "Křestní jméno" %>
      <%= f.input :last_name, label: "Příjmení"  %>
    </div>

    <p>Čas na hlasování je jeden měsíc.</p>

  </div>
  <div class="modal-footer">
    <div class="form-actions">
      <%= f.button :submit, value: "Odeslat", class: "btn btn-success" %>
    </div>
  </div>
<% end %>

app/views/ideas/edit.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="col-md-8">

      <h1>Editing Idea</h1>

      <%= render 'form' %>

      <%= link_to 'Show', @idea %> |
      <%= link_to 'Back', ideas_path %>
      <%= link_to 'Votes', idea_votes_path(@idea) %>
    </div>
  </div>
</div>

app/views/ideas/index.html.erb
<div id="listing">
  <div class="row">
    <div style="padding: 0 20px;">
      <div class="col-xs-12" style="display: flex; flex-direction: row-reverse; align-items: center">
        <span class="btn btn-lg btn-custom-inverse " data-toggle="modal" data-target="#myModal">VLOŽIT <i
        class="glyphicon glyphicon-plus"></i></span>

        <h1 style="flex-grow: 1;">Vlož svůj nápad a sdílej</h1>
      </div>
    </div>
  </div>

  <div class="break-line"></div>

  <section id="voting">
    <div class="row">
      <div style="padding: 10px 35px 10px 35px;">
        <h1>Lajkuj nápady, které chceš, aby se řešily</h1>
      </div>
    </div>
    <div class="row">
      <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
          <% Idea.active.all.each_with_index do |idea, index| %>
              <div class="panel panel-default <%= cookies[:voted_ideas].split(',').include?(idea.id.to_s) ? "vote-disabled" : "" %>">
                <a role="button" data-toggle="collapse" data-target="#collapse<%= idea.id %>" href="#collapse<%= idea.id %>">
                  <div class="panel-heading" role="tab" id="heading<%= idea.id %>">
                    <% if cookies[:voted_ideas].split(',').include?(idea.id.to_s) %>
                      <h3 class="downvote"><%= idea.down_votes.count %></h3>
                      <h3 class="upvote"><%= idea.up_votes.count %></h3>
                    <% else %>
                      <%= render 'votes/form', idea: idea %>
                    <% end %>

                    <h4 class="panel-title">
                      <%= idea.title %>
                    </h4>
                  </div>
                </a>

                <div id="collapse<%= idea.id %>" class="panel-collapse collapse" role="tabpanel"
                     aria-labelledby="heading<%= idea.id %>">
                  <div class="panel-body">
                    <%= idea.content %>
                  </div>
                </div>
              </div>
          <% end %>
        </div>

    </div>


    <div class="row">
      <div style="padding: 10px 35px 10px 35px;">
        <h1>Nápady, které jste poslali škole</h1>
      </div>
    </div>

    <div class="row">
      <div class="panel-group" id="sentaccordion" role="tablist" aria-multiselectable="true">
        <% (Idea.all - Idea.active.all).each_with_index do |idea, index| %>
            <div class="panel panel-default vote-disabled">
              <a role="button" data-toggle="collapse" data-target="#sent<%=  idea.id %>" href="#sent<%=  idea.id %>">
                <div class="panel-heading" role="tab" id="sentheading<%=  idea.id %>">
                  <h3 class="downvote"><%= idea.down_votes.count %></h3>
                  <h3 class="upvote"><%= idea.up_votes.count %></h3>
                  <h4 class="panel-title">
                    <%=  idea.title %>
                  </h4>
                </div>
              </a>
              <div id="sent<%=  idea.id %>" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading<%=  idea.id %>">
                <div class="panel-body">
                  <%=  idea.content %>
                </div>
              </div>
            </div>
        <% end %>
      </div>
    </div>
  </section>

  <!-- Modal -->
  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <%= render('ideas/modal_form') %>
      </div>
    </div>
  </div>
</div>

app/views/ideas/new.html.erb
<h1>New Idea</h1>

<%= render 'form' %>

<%= link_to 'Back', ideas_path %>

app/views/ideas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @idea.user_id %>
</p>

<p>
  <strong>Content:</strong>
  <%= @idea.content %>
</p>

<p>
  <strong>Title:</strong>
  <%= @idea.title %>
</p>

<p>
  <strong>First name:</strong>
  <%= @idea.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @idea.last_name %>
</p>

<p>
  <strong>Timeout at:</strong>
  <%= @idea.timeout_at %>
</p>

<%= link_to 'Edit', edit_idea_path(@idea) %> |
<%= link_to 'Back', ideas_path %>
<%= link_to 'Votes', idea_votes_path(@idea) %>

app/views/layouts/_footer.html.erb
<!-- Footer -->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
            </div>
        </div>
    </div>
</footer>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<!-- Navigation -->
<nav class="navbar navbar-default" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <!-- navbar-brand is hidden on larger screens, but visible when the menu is collapsed -->
            <%= link_to 'Business Casual', root_path, class: 'navbar-brand' %>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <%= render 'layouts/navigation_links' %>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li>
    <%= link_to 'Home', root_path %>
</li>
<li>
    <%= link_to 'About', page_path('about') %>
</li>
<li>
    <%= link_to 'Blog', page_path('blog') %>
</li>
<li>
    <%= link_to 'Contact', page_path('contact') %>
</li>

app/views/layouts/application.html.erb
<!doctype html>
<html class="no-js" lang="">
<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title></title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => false %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" media="all" href="/main.css" data-turbolinks-track="false" />
</head>
<body>
  <!--[if lt IE 8]>
  <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade
    your browser</a> to improve your experience.</p>
  <![endif]-->
  <section id="header">
    <nav class="navbar navbar-default"
         style="background: transparent; border-bottom: 4px solid #FF3574; border-radius: 0;">
      <%= image_tag("icon_smile_lickit.png", class: "lickit-bg") %>

      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <a class="navbar-brand" style="color: #FF3574; font-size: 1.5em" href="#">Zlepši školu!</a>
        </div>
      </div>
      <!-- /.container-fluid -->
    </nav>
  </section>

    <div id="content">
      <div class="container-fluid">
        <%= render 'layouts/messages' %>
        <%= yield %>
        <%= render 'layouts/footer' %>
      </div>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<div class="brand">Business Casual</div>
<div class="address-bar">3481 Melrose Place | Beverly Hills, CA 90210 | 123.456.7890</div>

<%= render 'layouts/navigation' %>

<div class="container">

    <div class="row">
        <div class="box">
            <div class="col-lg-12">
                <hr>
                <h2 class="intro-text text-center">About
                    <strong>business casual</strong>
                </h2>
                <hr>
            </div>
            <div class="col-md-6">
                <img class="img-responsive img-border-left" src="http://ironsummitmedia.github.io/startbootstrap-business-casual/img/slide-2.jpg" alt="">
            </div>
            <div class="col-md-6">
                <p>This is a great place to introduce your company or project and describe what you do.</p>
                <p>Lid est laborum dolo rumes fugats untras. Etharums ser quidem rerum facilis dolores nemis omnis fugats vitaes nemo minima rerums unsers sadips amets.</p>
                <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>

    <div class="row">
        <div class="box">
            <div class="col-lg-12">
                <hr>
                <h2 class="intro-text text-center">Our
                    <strong>Team</strong>
                </h2>
                <hr>
            </div>
            <div class="col-sm-4 text-center">
                <img class="img-responsive" src="http://placehold.it/750x450" alt="">
                <h3>John Smith
                    <small>Job Title</small>
                </h3>
            </div>
            <div class="col-sm-4 text-center">
                <img class="img-responsive" src="http://placehold.it/750x450" alt="">
                <h3>John Smith
                    <small>Job Title</small>
                </h3>
            </div>
            <div class="col-sm-4 text-center">
                <img class="img-responsive" src="http://placehold.it/750x450" alt="">
                <h3>John Smith
                    <small>Job Title</small>
                </h3>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>

</div>
<!-- /.container -->

app/views/pages/blog.html.erb
<div class="brand">Business Casual</div>
<div class="address-bar">3481 Melrose Place | Beverly Hills, CA 90210 | 123.456.7890</div>

<%= render 'layouts/navigation' %>

<div class="container">

    <div class="row">
        <div class="box">
            <div class="col-lg-12">
                <hr>
                <h2 class="intro-text text-center">Company
                    <strong>blog</strong>
                </h2>
                <hr>
            </div>
            <div class="col-lg-12 text-center">
                <img class="img-responsive img-border img-full" src="http://ironsummitmedia.github.io/startbootstrap-business-casual/img/slide-1.jpg" alt="">
                <h2>Post Title
                    <br>
                    <small>October 13, 2013</small>
                </h2>
                <p>Lid est laborum dolo rumes fugats untras. Etharums ser quidem rerum facilis dolores nemis omnis fugats vitaes nemo minima rerums unsers sadips amets. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>
                <a href="#" class="btn btn-default btn-lg">Read More</a>
                <hr>
            </div>
            <div class="col-lg-12 text-center">
                <img class="img-responsive img-border img-full" src="http://ironsummitmedia.github.io/startbootstrap-business-casual/img/slide-2.jpg" alt="">
                <h2>Post Title
                    <br>
                    <small>October 13, 2013</small>
                </h2>
                <p>Lid est laborum dolo rumes fugats untras. Etharums ser quidem rerum facilis dolores nemis omnis fugats vitaes nemo minima rerums unsers sadips amets. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>
                <a href="#" class="btn btn-default btn-lg">Read More</a>
                <hr>
            </div>
            <div class="col-lg-12 text-center">
                <img class="img-responsive img-border img-full" src="http://ironsummitmedia.github.io/startbootstrap-business-casual/img/slide-3.jpg" alt="">
                <h2>Post Title
                    <br>
                    <small>October 13, 2013</small>
                </h2>
                <p>Lid est laborum dolo rumes fugats untras. Etharums ser quidem rerum facilis dolores nemis omnis fugats vitaes nemo minima rerums unsers sadips amets. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>
                <a href="#" class="btn btn-default btn-lg">Read More</a>
                <hr>
            </div>
            <div class="col-lg-12 text-center">
                <ul class="pager">
                    <li class="previous"><a href="#">&larr; Older</a>
                    </li>
                    <li class="next"><a href="#">Newer &rarr;</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>

</div>
<!-- /.container -->

app/views/pages/contact.html.erb
<div class="brand">Business Casual</div>
<div class="address-bar">3481 Melrose Place | Beverly Hills, CA 90210 | 123.456.7890</div>

<%= render 'layouts/navigation' %>

<div class="container">

    <div class="row">
        <div class="box">
            <div class="col-lg-12">
                <hr>
                <h2 class="intro-text text-center">Contact
                    <strong>business casual</strong>
                </h2>
                <hr>
            </div>
            <div class="col-md-8">
                <!-- Embedded Google Map using an iframe - to select your location find it on Google maps and paste the link as the iframe src. If you want to use the Google Maps API instead then have at it! -->
                <iframe width="100%" height="400" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.com/maps?hl=en&amp;ie=UTF8&amp;ll=37.0625,-95.677068&amp;spn=56.506174,79.013672&amp;t=m&amp;z=4&amp;output=embed"></iframe>
            </div>
            <div class="col-md-4">
                <p>Phone:
                    <strong>123.456.7890</strong>
                </p>
                <p>Email:
                    <strong><a href="mailto:name@example.com">name@example.com</a></strong>
                </p>
                <p>Address:
                    <strong>3481 Melrose Place
                        <br>Beverly Hills, CA 90210</strong>
                </p>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>

    <div class="row">
        <div class="box">
            <div class="col-lg-12">
                <hr>
                <h2 class="intro-text text-center">Contact
                    <strong>form</strong>
                </h2>
                <hr>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugiat, vitae, distinctio, possimus repudiandae cupiditate ipsum excepturi dicta neque eaque voluptates tempora veniam esse earum sapiente optio deleniti consequuntur eos voluptatem.</p>
                <form role="form">
                    <div class="row">
                        <div class="form-group col-lg-4">
                            <label>Name</label>
                            <input type="text" class="form-control">
                        </div>
                        <div class="form-group col-lg-4">
                            <label>Email Address</label>
                            <input type="email" class="form-control">
                        </div>
                        <div class="form-group col-lg-4">
                            <label>Phone Number</label>
                            <input type="tel" class="form-control">
                        </div>
                        <div class="clearfix"></div>
                        <div class="form-group col-lg-12">
                            <label>Message</label>
                            <textarea class="form-control" rows="6"></textarea>
                        </div>
                        <div class="form-group col-lg-12">
                            <input type="hidden" name="save" value="contact">
                            <button type="submit" class="btn btn-default">Submit</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

</div>
<!-- /.container -->

app/views/votes/_form.html.erb
<h3 class="downvote">
  <%= simple_form_for([idea, idea.votes.new]) do |f| %>

    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.hidden_field :idea_id %>
      <%= f.hidden_field :state, value: false %>
    </div>

      <i class="glyphicon glyphicon-thumbs-down"></i>
<% end %>

</h3>

<h3 class="upvote">

<%= simple_form_for([idea, idea.votes.new]) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.hidden_field :idea_id %>
      <%= f.hidden_field :state, value: true %>
    </div>


      <i class="glyphicon glyphicon-thumbs-up"></i>

<% end %>
</h3>

app/views/votes/edit.html.erb
<h1>Editing Vote</h1>

<%= render 'form' %>

<%= link_to 'Show', @vote %> |
<%= link_to 'Back', votes_path %>

app/views/votes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Votes</h1>

<table>
  <thead>
    <tr>
      <th>Idea</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @votes.each do |vote| %>
      <tr>
        <td><%= vote.idea_id %></td>
        <td><%= link_to 'Show', vote %></td>
        <td><%= link_to 'Edit', edit_vote_path(vote) %></td>
        <td><%= link_to 'Destroy', vote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vote', new_idea_vote_path(@idea) %>

app/views/votes/new.html.erb
<h1>New Vote</h1>

<%= render 'form' %>

<%= link_to 'Back', ideas_path %>

app/views/votes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Idea:</strong>
  <%= @vote.idea_id %>
</p>

<%= link_to 'Edit', edit_vote_path(@vote) %> |
<%= link_to 'Back', votes_path %>